language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t zermaineeee/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true zermaineee/docker-react npm run test
